MC1_SERIAL_PORT_ADDRESS = '/dev/ttyACM0'
MC2_SERIAL_PORT_ADDRESS = '/dev/ttyACM1'

#SERIAL_SEND_EVENTS_TX FOR MC1 WHICH HANDLES OUTSIDE THE HOUSE EVENTS
O_SSE_TX_MOTION_LED_ON     = '1'
O_SSE_TX_MOTION_LED_OFF    = '2'
O_SSE_TX_MOTION_LED_AUTO   = '3'
O_SSE_TX_BUZZER_ON         = '4'
O_SSE_TX_BUZZER_OFF        = '5'
O_SSE_TX_MOTION_SENSOR_ON  = '6'
O_SSE_TX_MOTION_SENSOR_OFF = '7'

I_SSE_TX_LIGHT_LED_ON   = '1'
I_SSE_TX_LIGHT_LED_OFF  = '2'
I_SSE_TX_LIGHT_LED_AUTO = '3'

#SERIAL_SEND_EVENTS_RX
SSE_RX_OUTSIDE_SENSOR_ON        = 'O_MOTION_SENSORON'
SSE_RX_OUTSIDE_SENSOR_OFF       = 'O_MOTION_SENSORFF'
SSE_RX_OUTSIDE_LIGHT_SENSOR_ON  = 'O_LIGHT_SENSOR_HIGH'
SSE_RX_OUTSIDE_LIGHT_SENSOR_OFF = 'O_LIGHT_SENSOR_LOW'
