MC1_SERIAL_PORT_ADDRESS = '/dev/ttyACM0'
MC2_SERIAL_PORT_ADDRESS = '/dev/ttyACM1'

#SERIAL_SEND_EVENTS_TX FOR MC1 WHICH HANDLES OUTSIDE THE HOUSE EVENTS
O_SSE_TX_MOTION_LED_ON     = '1'
O_SSE_TX_MOTION_LED_OFF    = '2'
O_SSE_TX_BUZZER_ON         = '3'
O_SSE_TX_BUZZER_OFF        = '4'
O_SSE_TX_MOTION_SENSOR_ON  = '5'
O_SSE_TX_MOTION_SENSOR_OFF = '6'

#SERIAL_SEND_EVENTS_TX FOR MC2 WHICH HANDLES INSIDE THE HOUSE EVENTS
I_SSE_TX_LIGHT_LED_ON   = '1'
I_SSE_TX_LIGHT_LED_OFF  = '2'
I_SSE_TX_MOTION_LED_ON  = '1'
I_SSE_TX_MOTION_LED_OFF = '2'
I_SSE_TX_VENT_ON        = '3'
I_SSE_TX_VENT_OFF       = '4'
I_SSE_TX_HEAT_ON        = '5'
I_SSE_TX_HEAT_OFF       = '6'
I_SSE_TX_BUZZER_ON      = '7'
I_SSE_TX_BUZZER_OFF     = '8'

#SERIAL_RECEIVE_EVENTS_RX
SSE_RX_OUTSIDE_SENSOR_ON        = 'O_MOTION_SENSORON'
SSE_RX_OUTSIDE_SENSOR_OFF       = 'O_MOTION_SENSORFF'
SSE_RX_OUTSIDE_LIGHT_SENSOR_ON  = 'O_LIGHT_SENSOR_HIGH'
SSE_RX_OUTSIDE_LIGHT_SENSOR_OFF = 'O_LIGHT_SENSOR_LOW'

SSE_RX_INSIDE_TEMP_VAL          = 'I_TEMP_SESOR_VAL'
SSE_RX_INSIDE_LIGHT_SENSOR_ON   = 'I_LIGHT_SENSOR_HIGH'
SSE_RX_INSIDE_LIGHT_SENSOR_OFF  = 'I_LIGHT_SENSOR_LOW'
SSE_RX_INSIDE_FLAME_SENSOR_ON   = 'I_FLAME_SENSOR_HIGH'
SSE_RX_INSIDE_FLAME_SENSOR_OFF  = 'I_FLAME_SENSOR_LOW'
